---
###############################################################################
# GRAPHQL MODULE PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pipelines/applications/graphql-module-pipeline.yml'
    ref: 'v2.2.1'

variables:
  GRAPHQL_IMAGE: 'digipolis/dams-graphql'

